### ISSUE TITLE
Reference to MiscUtils.MixIn

### ISSUE THREAD

**Issue by nlgio** [nlgio/w4py3-middlekit#2]
Needs a patch and undecided howto integrate with w4py3

**Comment by jasonhildebrand** [comment]
One option would be to copy MixIn into MiddleKit, so that MiddleKit doesn't have an external dependency on this.  The actual MixIn class is only about 80 lines, half of which are comments.

**Comment by Cito** [comment]
The problem with the old MixIn function is that it was written when Python had only old style functions. It did not work properly with new style functions, which are the new default in Python 3, and nobody ever noticed, since there were no unit tests.

I have been trying to fix that and also add unit tests in w4py3 (https://github.com/Cito/w4py3/commit/df710b603e0dabcd30f4db9671be67f27fafef4d). Let me know if that fix solves your problems, or what to further improve.

**Comment by nlgio** [comment]
hi, thats perfect, problem fixed. Thanks.

**Comment by nlgio** [comment]
another option would be to include MiscUtils and WebUtils as external references with fallback to local copy

**Comment by jasonhildebrand** [comment]
What would be the advantage?  I feel that a local copy follows the KISS principle best, it's simple, predictable and consistent.

**Comment by Cito** [comment]
It violates the DRY and SPOT principles though. If the code in Webware and MiddleKit starts to deviate (and it will over time), then usage is not predictable and consistent any more.

One crucial question you need to decide first is whether MiddleKit should be distributed as a standalone package than can *also* be used as a Webware plugin (not sure whether this makes sense), or whether it should be used as a webware plugin *exclusively*. In the former case, it would make more sense to have local copies of the utility stuff it uses from Webware, in the latter case I would rather not duplicate.

**Comment by jasonhildebrand** [comment]
Good points all around.  I think that MiddleKit would mostly have been used together with Webware -- especially since it was bundled together with Webware -- and that it's very reasonable for us to not support other use cases.
That suggests the options are to include MiscUtils and WebUtils as external references, or to revisit the decision to separate MiddleKit out from the Webware repo.

**Comment by nlgio** [comment]
assumed bundling and therefore handled MiscUtils and WebUtils as external references. Standalone users just see an dependancy which should be ok.

**Comment by jasonhildebrand** [comment]
Tried things out today, hit a minor issue with the version numbers.   w4py3-middlekit should be updated to require Webware-for-Python >= 3.0.0a  (not 3.0.0 which doesn't exist yet).

Even after making this fix locally, I was not able to install w4py3 and w4py3-middlekit together in "develop" mode (using pip3 install -e '/path/to/git/checkout').  When I tried, Webware failed to find MiddleKit:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/webware/Scripts/WaitressServer.py", line 63, in serve
      exec(script, scriptVars)
  File "<string>", line 31, in <module>
  File "/usr/local/lib/python3.7/dist-packages/webware/Application.py", line 240, in __init__
      self.loadPlugIns()
  File "/usr/local/lib/python3.7/dist-packages/webware/Application.py", line 1123, in loadPlugIns
      in pkg_resources.iter_entry_points('webware.plugins')
  File "/usr/local/lib/python3.7/dist-packages/webware/Application.py", line 1124, in <listcomp>
      if entry_point.name in plugInNames
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
      return self.resolve()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'webware.MiddleKit'
```

My workaround was to symlink MiddleKit into the webware tree:

```
cd src/w4py3/webware
ln -s ../../w4py3-middlekit/webware/MiddleKit/ .
```

Then everything worked OK.  Since this only affects MiddleKit developers (not users of MiddleKit), I don't view it as a critical issue, but I thought I would post this in case anyone else runs into this problem in the future.

When I installed them both normally (not in develop mode), it worked fine.
